# -*- coding: utf-8 -*-
"""
/***************************************************************************
 LoginForm
                                 A QGIS plugin
 This plugin is used to enter authentication credentials to access a restricted page or form
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2020-02-05
        copyright            : (C) 2020 by Vineetha Antony
        email                : vinif@yahoo.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load LoginForm class from file LoginForm.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .login_form import LoginForm
    return LoginForm(iface)
